<?php 
    $html = $this->getApiTemplate();
    if (!empty($html)):
        $html = '<form id="elefunds-form">' . $html . '</form>';
        echo $html;
?>    
    <script type="text/javascript">
    //<![CDATA[
        var ElefundsForm = Class.create();
        ElefundsForm.prototype = {
            initialize: function(form) {
                this.form = form;
            }
        }
        
        eleForm = new ElefundsForm($('elefunds-form'));

        Review.prototype.save = function(){
            if (checkout.loadWaiting!=false) return;
            checkout.setLoadWaiting('review');
            var params = Form.serialize(payment.form);
            if (this.agreementsForm) {
                params += '&'+Form.serialize(this.agreementsForm);
            }
            if (eleForm.form) {
                params += '&'+Form.serialize(eleForm.form);
            }
            
            params.save = true;
            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method:'post',
                    parameters:params,
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout)
                }
            );
        };
    //]]>
    </script>
<?php 
    endif;
?>

