<?php if ($this->canShowBanner()): ?>

<div id="elefunds" style="border-width: 0 1px; border-style: solid; border-color: #d9dde3;"></div>
<div id="donation-form"></div>

<script type="text/javascript">
    window.elefundsOptions = <?php echo $this->getJson(); ?>;
    console.log(window.elefundsOptions);
    require([
        'jquery',
        'elefunds-app'
    ], function ($, ElefundsApplication) {
        'use strict';

        if ($('#elefunds').length || $('#elefunds-share').length) {
            ElefundsApplication.initialize();
        }
    });

    //<![CDATA[
    if (typeof Review !== 'undefined') {

        /*
         * One page checkout specific JS
         */

        var ElefundsForm = Class.create();
        ElefundsForm.prototype = {
            initialize: function(form) {
                this.form = form;
            }
        };

        elefundsForm = new ElefundsForm($('donation-form'));

        Review.prototype.save = function() {
            if (checkout.loadWaiting!=false) return;
            checkout.setLoadWaiting('review');
            var params = Form.serialize(payment.form);
            if (this.agreementsForm) {
                params += '&'+Form.serialize(this.agreementsForm);
            }
            if (elefundsForm.form) {
                params += '&'+Form.serialize(elefundsForm.form);
            }

            params.save = true;
            var request = new Ajax.Request(
                    this.saveUrl,
                    {
                        method:'post',
                        parameters:params,
                        onComplete: this.onComplete,
                        onSuccess: this.onSave,
                        onFailure: checkout.ajaxFailure.bind(checkout)
                    }
            );
        };
    }
    //]]>
</script>

<?php endif; ?>