<?php if ($this->canShowBanner()): ?>

<div id="elefunds"></div>
<div id="donation-form"></div>

<script type="text/javascript">
    window.elefundsOptions = <?php echo $this->getJson(); ?>;
    console.log(window.elefundsOptions);
    require([
        'jquery',
        'elefunds-app'
    ], function ($, ElefundsApplication) {
        'use strict';

        if ($('#elefunds').length || $('#elefunds-share').length) {
            ElefundsApplication.initialize();
        }
    });

</script>

<?php endif; ?>